---
title: "Capstone Project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# SpringBoard Data Science Capstone Project May 2017

## Topic: Addressing student skills and employer needs

**The problem:** Students spend a small fortune getting a college degree, but how do they know which skills lead to good paying jobs? In fact, only 4 in 10 college seniors feel their college experience has been very helpful in preparing for a career, according to a study by McGraw-Hill Education’s 2016 [annual Workforce Readiness Survey](http://www.multivu.com/players/English/7782351-mcgraw-hill-education-survey/). What's clear is that students often feel a disconnect between what they are learning in school and what employers are truly looking for.

Even more troubling, according to a [report](https://www.newyorkfed.org/medialibrary/media/research/current_issues/ci20-1.pdf) done by the New York Reserve Bank in January of 2017, they found that 33% of college graduates were underemployed at jobs that don't require a college degree. This, the report claims, is due to a lack of of collaboration between higher education and businesses looking to hire. 

Although college is also meant to promote good citizenship and develop students' critical thinking skills, it is, in part, also expected to produce candidates with industry-ready, time-sensitive career skills. With the latter objective in mind, the New York Fed suggests that the best way to promote better outcomes for college graduates and acquire job-ready skills is to "develop a fuller understanding of the relationship between their own curriculum, the needs of employers... and the most valuable skills to build while in school." Clearly, what needs to be done is to bridge the gap between what higher education is currently offering its students and what companies are truly looking for.

**The client:** The client for this project will be a university, let's say the University of Miami. With this project's analysis, the university will have real-time information about what skills employers in Miami are looking for in their grads, how much they are willing to pay to fill those positions, and the top jobs in their area. The goal is to create a curriculum extremely up to date and relevent for graduates to feel truly prepared to enter the workforce and land the job of their dreams.

The data:


1. Mine data from job boards that include the top skills to have and use that information to develop a "relevent" college curriculum.


2. Utilize the Indeed job search engine API to analyze job postings in the Miami area.

**Outline/Approach:**

1. Use Indeed API

2. Tidy data

3. Exploratory data analysis, focusing on skill requirements, job titles, salaries, and location

4. Summarize findings in deliverables listed below and publish to the Springboard community.

**Deliverables:**

1. Code

2. Paper and/or slide deck